[package]
name = "system76_ectool"
version = "0.1.3"
edition = "2018"
description = "System76 EC tool"
license = "MIT"
authors = ["Jeremy Soller <jeremy@system76.com>"]
repository = "https://github.com/system76/ec"

[lib]
name = "ectool"

[dependencies]
redox_hwio = "0.1.1"

[features]
default = ["std"]
stable = ["redox_hwio/stable"]
std = []
